<?php

namespace Database\Factories\Goods;

use App\Models\Goods\Goods;
use App\Models\Goods\GoodsSpecification;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Goods\GoodsProduct>
 */
class GoodsProductFactory extends Factory
{

    public function set($key, $value)
    {
        return parent::set($key, $value); // TODO: Change the autogenerated stub
    }

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $goods = Goods::factory()->create();
        $spec = GoodsSpecification::factory()->create(['goods_id' => $goods->id]);
        return [
            'goods_id'      => $goods->id,
            'specifications' => [$spec->value],
            'price'         => 999,
            'number'        => 100,
            'url'           => 'http://yanxuan.nosdn.127.net/3bd73b7279a83d1cbb50c0e45778e6d6.png'
        ];
    }
}
